# Generated by Django 3.1.7 on 2021-03-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210330_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='movies.Category'),
        ),
    ]
