# Generated by Django 3.1.7 on 2021-03-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210330_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'verbose_name_plural': 'Cast'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name_plural': 'Ratings'},
        ),
    ]
